### ISSUE TITLE
IsInitialized starts true

### ISSUE THREAD

**Issue by evilC** [WootingKb/wooting-analog-wrappers#3]
Using this code, `IsInitialized` starts off true, is this intentional?
```
namespace TestApp
{
    class Program
    {
        static void Main(string[] args)
        {
            var isInitialized = WootingAnalogSDK.IsInitialised;
        }
    }
}
```

**Comment by simon-wh** [comment]
I don't know how it ends up being true, but I was able to replicate it with the release sdk, but can't replicate it with the current dev sdk so it looks to have been sorted

**Comment by simon-wh** [comment]
I'm pretty sure this is not an issue in v0.4.0. Could you update to v0.4.0 Analog SDK and the latest nuget package and verify this is the case on your end?
